language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

env:
  global:
  - secure: "TA57VVPkeoIcFqWIILtcTZXfOEjHwXdEhGXjTvqOr/3Yc7vJNob6dTqp335sZNF0vu1NwUYFYcHhYqJOHlYAVPOXZUe0W2uuROQPFe7BUwI3B5rXfezv7+AYiDrNI09GALADt4xPVjZ+b7OrmnpJhajlh+tsvofYBNPi0H4B6ueLZaKNmeyShoje1KcJSrT3p7AYJ1iPZ3bdi+iTkArJhFhLXi2CJKe78yEPE+111+05B76541tJI20EtEVmkXEdBn4pUXb6/ec7WoT5MV4QRo5SanUhcdgZtsO3e6WiyPmZVQkOyABwjSRLE2o+sPI2aJSbwKBPGmszug7e/7nFbFojWJE/ewKngMEK+wRPcgEvoCK+zjSfBmw4qaLGujf3l7zPiYa9FA26d1Qn3ylIrCQMIrLGn5zJyNvDVZUBiU8dn5jvRl+1So+YPe4bpXSctkhu6b3squmQ4QmbAnGFtL8N4tzXzqb9rvcNvSNp20Uz+GcpTvZsLowt9WHqwbfWTbUWu5DudvJQnPAlj7WkPEWaZwG9Vcnh/khZ4ErvMhvbnRksklnzU45BSIrgiWALkHni3wDYSr+sKqwEuwQ9IdR7zw2spbG0d8xucdZaTyNiS8zziW7Q4u/Qn8Z6xfnHPzZXfXx3X0RR/adplexdOKEiy6gS/HgHh37GZl27+Tk="
  - secure: "TC8faB3C1ESQjy0ggm4B23NC+0Tc3aozORLLd3GxxygUDIes2VCjLloafqhW3t5Xa9JKXaiTRQFh4+hXbqIsNIRAQR+ncbGANp/CyOZDGKwV7DZ5ThIGJgzut2ueYs4iKvOxNLtV8uULwgOmX4yDJuDRTkYwXD1TgJ5kqfjLdK/ZDzxbFnD6PrwA7XupESNjIyBjO3NCTcdsUa1xG69W7kK5ikd6TOlHcIHPYAehfxnqtQxwrNEBljx4hGYh/HDLACue3QTmi8mjAQ4fuIdkFxJSXKVJ0XlylBHNHmeJsMH7eZiNq4ZIZ/eIoGXKyepn/qhyFNLmkCqcmdCfbhAj8MkkaEea/WOlcP85rmXVV2fr1nTXQrx/TOQLKHYkvqCZimKmyrMWnqJlj1lToYW8xPT/GNprIRA4DrYeE/9co2lAuXLX+mEFsaYghABY0aypYUh4ZwUzTXsO7C8vYqw3ZADogcifqPX0HbSqkPB9vbODt/2nZ663NXXeUerpGaEhIvM3d3nPnaIoDwd7YLLAvC3XDknNwl8lebLv5lBeL73mjusXIOdozceiRNhE7ehkkShGgZOn0hRl6yYoMQXoi7LqcuZgwtnrFOuL6PhgihOb4WqheJGeP57a0MicKf9JZewKuaimX5uRPwnGIV9a9ONfP073Qqr9gV7wZMto+m4="

addons:
  apt:
    packages:
    - cmake

script:
- cargo build --all-features --verbose
- cargo test --all-features --verbose

after_success:
- |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc --all-features --no-deps &&
  git clone https://github.com/davisp/ghp-import &&
  ./ghp-import/ghp_import.py -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
- |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo publish --token ${CRATESIO_TOKEN}
