language: rust

rust:
- nightly

env:
  global:
  - secure: dPnlbtp/I74TtNHkQJM7G+fn80RkIaWOqXvI/byYKfjfB5ZOC6gPc77GJ0+A+ZJXZEoFct4Tt1eUKs+hz0jLfs0kcPb8XArTj+nJbgnLeBREdGU5r+NN4D005zOJJR5VOuVViUxfJooQOI+ug6v8tRXE4cfXipy9QFUGJmJL+HyJNBtJyjqkZAvI9l3oWQBxbhnO2cdvg2oOzqZhM/xMSzPzLCW6fA0pBs5ifkMIHsS5zLbt2nFue7b84OdnYvgUNc9mFgpKVoTm27ypEnIGysGDBOa8ZaSVwW8VRabRftDVP5Ht0JYZ4R/P1LcHjXR8x/zR15BPxqAjEf9AKam6kC1o/t9wgBokCvYuQGbmeq45MPyIlJmZ8kcH7qejnAHOF8UyJTFZk1SfIJ7JXm/wLnicBQuVHNywPDv7zQ0vICnV6i0dvrcjFUxewT/E8ErLCK7NoKmxtm6RRkkG8Hcbfc4rRvIoxIK30FV03hT7G0lYLIvwEBtFCC+FtCKrOun9wnEanTjMBmmCqG26mJZOdztGlFFlEwO22DaBolSjwrvwXOieUlZ+hiC183qsivD2zb8NS/CAnxmwybhMEAPOVVlqzlVgKLYP0Zyf+8vFR0RvLe7M0jGX8eJekNETegt9SNJ6PkVpqwgPuMDA0Og9JuONDJnDkFvxh9Z5Tkrq/eE=

addons:
  apt:
    packages:
    - cmake

before_install:
- git clone https://github.com/erincatto/Box2D
- cd Box2D/Box2D
#- export BOX2D_INCLUDE_PATH=$PWD
- cd Build
- cmake -DBOX2D_INSTALL=ON -DBOX2D_BUILD_SHARED=ON -DBOX2D_BUILD_EXAMPLES=OFF ..
- make && sudo make install
- sudo ldconfig
- cd ../../..

script:
- cargo build --verbose
- cargo test --verbose

after_success:

- |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  git clone https://github.com/davisp/ghp-import &&
  ./ghp-import/ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
