[package]

name = "box2d"
description = "Rust binding for Box2D"
version = "0.2.2"
authors = ["Thomas Koehler <basta.t.k+git@gmail.com>"]

repository = "https://github.com/Bastacyclop/rust_box2d.git"
license = "zlib"

build = "build_frontend.rs"

[lib]

name = "box2d"

[dependencies]

bitflags = "*"
