[package]

name = "box2d"
version = "0.2.2"
description = "Rust binding for Box2D"
keywords = ["physics", "bindings", "box2d"]
authors = ["Thomas Koehler <basta.t.k+git@gmail.com>"]
license = "zlib"
readme = "README.md"
repository = "https://github.com/Bastacyclop/rust_box2d.git"

build = "build_frontend.rs"

[lib]
name = "box2d"

[build-dependencies]
gcc = "*"

[dependencies]
libc = "*"
vec_map = "*"
bitflags = "*"

[dev_dependencies.box2d_testbed]
path = "testbed"

[dev_dependencies]
piston = "*"
