[package]

name = "box2d"
description = "Rust binding for box2d"
version = "0.2.1"
authors = ["Thomas Koehler <basta.t.k+git@gmail.com>"]

repository = "https://gitlab.com/Bastacyclop/rust_box2d"
license = "GPLv3"

build = "build_frontend.rs"

[lib]

name = "box2d"
