[package]

name = "box2d_testbed"
version = "0.1.0"
authors = ["Thomas Koehler <basta.t.k+git@gmail.com>"]

[lib]
name = "testbed"

[dependencies]
piston = "0.5"
pistoncore-glutin_window = "0.7"
piston2d-graphics = "*"
piston2d-opengl_graphics = "0.6"

[dependencies.box2d]
path = ".."
