name: Publish Documentation

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "pages"
  cancel-in-progress: false

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  contents: read
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cmake
      run: sudo apt-get install cmake
    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v4
    - name: Build Docs
      run: |
        cargo doc --no-deps --all-features --verbose
        echo "<meta http-equiv=\"refresh\" content=\"0; url=wrapped2d\">" > target/doc/index.html
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './target/doc'
 
  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
